name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: docker build -f docker/Dockerfile -t tiny-data-sync-test .

      - name: Run bats suite
        run: docker run --rm tiny-data-sync-test bats tests/td_sync.bats
